# Generated by Django 5.2 on 2026-02-01 17:19

import workplaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplace',
            options={'ordering': ['table_number'], 'verbose_name': 'Рабочее место', 'verbose_name_plural': 'Рабочие места'},
        ),
        migrations.AlterField(
            model_name='workplace',
            name='table_number',
            field=models.CharField(max_length=20, unique=True, validators=[workplaces.models.validate_table_number], verbose_name='Номер стола'),
        ),
    ]
