# Generated by Django 5.2 on 2026-02-04 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сбора')),
                ('occasion', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('graduation', 'Выпускной'), ('medical', 'Лечение'), ('charity', 'Благотворительность'), ('event', 'Мероприятие'), ('other', 'Другое')], max_length=20, verbose_name='Повод')),
                ('description', models.TextField(verbose_name='Описание')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Целевая сумма')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Собрано')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collects/covers/%Y/%m/%d/', verbose_name='Обложка')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора')),
            ],
            options={
                'verbose_name': 'Групповой сбор',
                'verbose_name_plural': 'Групповые сборы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта')], default='card', max_length=20, verbose_name='Способ оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundraising.collect', verbose_name='Сбор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
