# Generated by Django 5.2 on 2026-02-04 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={},
        ),
        migrations.AlterField(
            model_name='payment',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fundraising.collect', verbose_name='Сбор'),
        ),
    ]
