# Generated by Django 5.2 on 2026-01-26 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-hire_date'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата приёма на работу'),
        ),
    ]
